"""Markdown file writer for activity logs."""

import logging
from pathlib import Path
from datetime import datetime
from typing import Optional, List

logger = logging.getLogger(__name__)


class MarkdownWriter:
    """Writes activity logs to Markdown files."""

    TABLE_HEADER = "| Time | Activity Description (Focus) | Background Context |\n"
    TABLE_SEPARATOR = "| --- | --- | --- |\n"

    def __init__(self, config_manager):
        """Initialize markdown writer.
        
        Args:
            config_manager: ConfigManager instance
        """
        self.config = config_manager
        self.output_dir = config_manager.output_directory
        self.current_date = None
        self.current_file_path = None

        # Ensure output directory exists
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def write_entry(
        self,
        timestamp: datetime,
        foreground_description: str,
        background_context: Optional[List[str]] = None
    ):
        """Write an activity entry to the log file.
        
        Args:
            timestamp: Timestamp of the activity
            foreground_description: Description of foreground activity
            background_context: List of background context strings
        """
        # Check if we need a new file (new day)
        date_str = timestamp.strftime("%Y-%m-%d")
        if date_str != self.current_date:
            self._initialize_new_log_file(date_str)

        # Format time
        time_str = timestamp.strftime("%H:%M")

        # Escape pipe characters in foreground description
        foreground_escaped = self._escape_pipe_chars(foreground_description)

        # Format background context and escape pipe characters
        if background_context and len(background_context) > 0:
            escaped_context = [self._escape_pipe_chars(ctx) for ctx in background_context]
            bg_str = "<br>".join(escaped_context)
        else:
            bg_str = "-"

        # Create table row
        row = f"| {time_str} | {foreground_escaped} | {bg_str} |\n"

        # Append to file
        try:
            with open(self.current_file_path, 'a', encoding='utf-8') as f:
                f.write(row)
            logger.debug(f"Wrote entry to {self.current_file_path}")
        except Exception as e:
            logger.error(f"Error writing to log file: {e}")

    def write_idle_entry(self, timestamp: datetime):
        """Write an IDLE entry to the log.
        
        Args:
            timestamp: Timestamp when idle was detected
        """
        self.write_entry(
            timestamp=timestamp,
            foreground_description="**[IDLE]**: No user activity",
            background_context=None
        )

    def _escape_pipe_chars(self, text: str) -> str:
        """Replace pipe characters to prevent breaking Markdown table format.
        
        Args:
            text: Text that may contain pipe characters
            
        Returns:
            Text with pipes replaced by dashes for better LLM readability
        """
        if not text:
            return text
        
        # Replace | with - (dash) for cleaner, more LLM-friendly text
        # This makes logs easier for AI models to parse and understand
        # Example: "Chat | John Smith" becomes "Chat - John Smith"
        return text.replace('|', ' - ')

    def _get_week_folder(self, date: datetime) -> str:
        """Return the week subfolder name for a given date.

        Example: 'Week 10 of 2026'
        """
        iso_year, iso_week, _ = date.isocalendar()
        return f"Week {iso_week} of {iso_year}"

    def _initialize_new_log_file(self, date_str: str):
        """Initialize a new log file for the given date.

        Args:
            date_str: Date string in YYYY-MM-DD format
        """
        self.current_date = date_str
        date = datetime.strptime(date_str, "%Y-%m-%d")
        week_folder = self._get_week_folder(date)
        week_dir = self.output_dir / week_folder
        week_dir.mkdir(parents=True, exist_ok=True)
        self.current_file_path = week_dir / f"{date_str}_log.md"

        # Check if file already exists
        if self.current_file_path.exists():
            logger.info(f"Appending to existing log file: {self.current_file_path}")
            return

        # Create new file with header and table structure
        try:
            with open(self.current_file_path, 'w', encoding='utf-8') as f:
                f.write(f"# Activity Log - {date_str}\n\n")
                f.write("Generated by Workday Activity Logger\n\n")
                f.write("---\n\n")
                f.write(self.TABLE_HEADER)
                f.write(self.TABLE_SEPARATOR)
            
            logger.info(f"Created new log file: {self.current_file_path}")
        except Exception as e:
            logger.error(f"Error creating log file: {e}")

    def get_current_log_path(self) -> Optional[Path]:
        """Get path to current log file.
        
        Returns:
            Path to current log file or None
        """
        return self.current_file_path
