"""Markdown file writer for activity logs."""

import logging
from pathlib import Path
from datetime import datetime
from typing import Optional, List

logger = logging.getLogger(__name__)


class MarkdownWriter:
    """Writes activity logs to Markdown files."""

    TABLE_HEADER = "| Time | Activity Description (Focus) | Background Context |\n"
    TABLE_SEPARATOR = "| --- | --- | --- |\n"

    def __init__(self, config_manager):
        """Initialize markdown writer.
        
        Args:
            config_manager: ConfigManager instance
        """
        self.config = config_manager
        self.output_dir = config_manager.output_directory
        self.current_date = None
        self.current_file_path = None

        # Ensure output directory exists
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def write_entry(
        self,
        timestamp: datetime,
        foreground_description: str,
        background_context: Optional[List[str]] = None
    ):
        """Write an activity entry to the log file.
        
        Args:
            timestamp: Timestamp of the activity
            foreground_description: Description of foreground activity
            background_context: List of background context strings
        """
        # Check if we need a new file (new day)
        date_str = timestamp.strftime("%Y-%m-%d")
        if date_str != self.current_date:
            self._initialize_new_log_file(date_str)

        # Format time
        time_str = timestamp.strftime("%H:%M")

        # Format background context
        if background_context and len(background_context) > 0:
            bg_str = "<br>".join(background_context)
        else:
            bg_str = "-"

        # Create table row
        row = f"| {time_str} | {foreground_description} | {bg_str} |\n"

        # Append to file
        try:
            with open(self.current_file_path, 'a', encoding='utf-8') as f:
                f.write(row)
            logger.debug(f"Wrote entry to {self.current_file_path}")
        except Exception as e:
            logger.error(f"Error writing to log file: {e}")

    def write_idle_entry(self, timestamp: datetime):
        """Write an IDLE entry to the log.
        
        Args:
            timestamp: Timestamp when idle was detected
        """
        self.write_entry(
            timestamp=timestamp,
            foreground_description="**[IDLE]**: No user activity",
            background_context=None
        )

    def _initialize_new_log_file(self, date_str: str):
        """Initialize a new log file for the given date.
        
        Args:
            date_str: Date string in YYYY-MM-DD format
        """
        self.current_date = date_str
        self.current_file_path = self.output_dir / f"{date_str}_log.md"

        # Check if file already exists
        if self.current_file_path.exists():
            logger.info(f"Appending to existing log file: {self.current_file_path}")
            return

        # Create new file with header and table structure
        try:
            with open(self.current_file_path, 'w', encoding='utf-8') as f:
                f.write(f"# Activity Log - {date_str}\n\n")
                f.write("Generated by Workday Activity Logger\n\n")
                f.write("---\n\n")
                f.write(self.TABLE_HEADER)
                f.write(self.TABLE_SEPARATOR)
            
            logger.info(f"Created new log file: {self.current_file_path}")
        except Exception as e:
            logger.error(f"Error creating log file: {e}")

    def get_current_log_path(self) -> Optional[Path]:
        """Get path to current log file.
        
        Returns:
            Path to current log file or None
        """
        return self.current_file_path
